<?php
require "config.php";
$current = requireLogin();
$memberId = (int) ($_GET["id"] ?? 0);
$statement = $conn->prepare("SELECT u.display_name, u.avatar_path, u.academic_level, u.profile_visibility, COUNT(r.id) AS shared_count, GROUP_CONCAT(DISTINCT a.label ORDER BY a.id SEPARATOR ', ') AS shared_levels FROM users u LEFT JOIN resources r ON r.submitted_by = u.id AND r.status = 'approved' LEFT JOIN academic_levels a ON a.id = r.academic_level_id WHERE u.id = ? GROUP BY u.id, u.display_name, u.avatar_path, u.academic_level, u.profile_visibility");
$statement->bind_param("i", $memberId); $statement->execute(); $member = $statement->get_result()->fetch_assoc(); $statement->close();
if (!$member) { http_response_code(404); exit("Member not found."); }
$shared = $conn->prepare("SELECT r.id, r.title, r.original_file_name, s.name AS subject_name, a.label AS level_name FROM resources r JOIN subjects s ON s.id = r.subject_id JOIN academic_levels a ON a.id = r.academic_level_id WHERE r.submitted_by = ? AND r.status = 'approved' ORDER BY r.created_at DESC");
$shared->bind_param("i", $memberId); $shared->execute(); $sharedResources = $shared->get_result();
?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= e($member["display_name"]) ?> | Resource Exchange</title><link rel="stylesheet" href="style.css?v=public-download-8"></head><body>
<header class="topbar"><a class="brand" href="index.php">Student Resource Exchange</a><nav><?php if ($current["role"] === "admin"): ?><a href="admin.php">Admin page</a><?php else: ?><a href="student.php">Student page</a><?php endif; ?><a href="users.php">Members</a><a href="profile.php">Profile</a><a href="logout.php">Log out</a></nav></header>
<main class="container narrow"><section class="panel public-profile"><img class="profile-avatar large" src="<?= e(avatarUrl($member["avatar_path"] ?? null)) ?>" alt="<?= e($member["display_name"]) ?> profile picture"><p class="eyebrow">PUBLIC PROFILE</p><h1><?= e($member["display_name"]) ?></h1><?php $isPrivate = ($member["profile_visibility"] ?? "public") === "private"; ?><p class="muted"><?= $isPrivate ? "Shared resources are private." : ((int) $member["shared_count"] . " approved resource" . ((int) $member["shared_count"] === 1 ? "" : "s") . " shared with the community.") ?></p><div class="public-details"><p><strong>Academic level:</strong> <?= e($member["academic_level"] ?: "Not provided") ?></p><?php if (!$isPrivate): ?><p><strong>Shared resource levels:</strong> <?= e($member["shared_levels"] ?: "No academic level shared yet") ?></p><?php endif; ?><p><strong>Contact:</strong> Private</p></div><?php if (!$isPrivate): ?><h2>Shared resources</h2><?php if (!$sharedResources->num_rows): ?><p class="muted">No approved resources shared yet.</p><?php else: ?><div class="public-resources"><?php while ($resource = $sharedResources->fetch_assoc()): ?><article class="public-resource"><strong><?= e($resource["title"]) ?></strong><span><?= e($resource["subject_name"]) ?> · <?= e($resource["level_name"]) ?></span><div class="resource-actions"><a class="download" href="resource_view.php?id=<?= (int) $resource["id"] ?>">Open resource</a><a class="download secondary-action" href="download.php?id=<?= (int) $resource["id"] ?>&download=1">Download</a></div></article><?php endwhile; ?></div><?php endif; ?><?php else: ?><p class="private-label">This member has chosen not to share resource information.</p><?php endif; ?><a class="download" href="users.php">Back to members</a></section></main></body></html>
